---
title: "R Notebook"
output: html_notebook
---

Load libraries
```{r}
library("tidyr")
library("plyr")
library('ggplot2')
library('dplyr')
library("glue")

wkdir = "~/Desktop/GitHub/Obesity/FCC"
setwd(wkdir)
savedir = "~/Desktop/GitHub/Obesity/FCC/Output_Figures"

source("~/Desktop/Obesity/OLD/FromKate/FD_functions.R")
```

FCC alignment dataframe set up
```{r}
flu_align = read.csv("flu.alignment.csv", header = TRUE, sep = ",")

flu_align = separate(flu_align, Sample, into = c("FerretID","DPI","Rep"))
flu_align$Sample = paste0(flu_align$FerretID,"_",flu_align$DPI,"_",flu_align$Rep)
flu_align$FerretID_DPI = paste0(flu_align$FerretID,"_",flu_align$DPI)

flu_align1 = filter(flu_align, Rep == "rep1")
flu_align2 = filter(flu_align, Rep == "rep2")

flu_align = merge(flu_align1, flu_align2, by = c("FerretID","DPI","FerretID_DPI"))

flu_align$TotalReads.avg = ((flu_align$TotalReads.x + flu_align$TotalReads.y) / 2)
```

FCC alignment plot
```{r}
FCC_align = ggplot(flu_align, aes(x = FerretID_DPI, y = log10(TotalReads.avg))) +
  geom_point() + 
  ylim(0,6) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  PlotTheme1
print(FCC_align)
ggsave("FCC_align.png", FCC_align, path = savedir)
```

Loading in coverage files
```{r}
cov = read.csv("H9N2.coverage.csv", header = TRUE, sep = ",")

seg_sizes = "SegmentSize.csv"
sizes = read.csv(file=seg_sizes,header=T,sep=",",na.strings = c(''))

SEGMENTS = c('H9N2_PB2','H9N2_PB1','H9N2_PA','H9N2_HA','H9N2_NP','H9N2_NA','H9N2_MP','H9N2_NS')
cov$segment = factor(cov$segment, levels = SEGMENTS)
```

Checking if data passes thresholds & make coverage plots
```{r}
cov_cutoff = 200
cov_check = CoverageAcross(cov,cov_cutoff,80,sizes, wkdir)
```

Loading in variant files & metadata
```{r}
varfile = "H9N2.VariantsOnly.0.01.200.csv"
metafile = "FCC_Metadata.csv"


# read and rearrange the data
vars = read.csv(file=varfile,header=T,sep=",",na.strings = c(''))
vars$name = vars$sample
meta = read.csv(file=metafile,header=T,sep=",",na.strings = c(''))
```

Specifying thresholds and plotting variables
```{r}
diet = c("Obese","Lean","Control")
dietColors = c("#FF9933","#66CCFF","#606060")
names(dietColors) = diet
DietcolScale_fill <- scale_fill_manual(name = "grp",values = dietColors)
DietcolScale <- scale_colour_manual(name = "grp",values = dietColors)

freq_cut = 0.02
pvalcut  = 0.05

ntlist = c("A","C","G","T")
SEGMENTS = c('H9N2_PB2','H9N2_PB1','H9N2_PA','H9N2_HA','H9N2_NP','H9N2_NA','H9N2_MP','H9N2_NS')
```

Rearranging variant dataframe
```{r}
vdf = ArrangeVarWRep(vars)
vdf = merge(vdf,meta, by = c("sample"))
```